### ISSUE TITLE
[Feature Request] Show operation could be easier to read

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/activity-log#12]
# Feature Request

### What I am trying to achieve

See the changes in an entry, where I logged everything (not just the dirty). To rephrase, the activity log entry contains the information about the fields that have changed, but also about the fields that have NOT changed. So it's got a lot of info.

Right now the Show view looks like this:
<img width="1289" alt="CleanShot 2023-08-29 at 10 50 26@2x" src="https://github.com/Laravel-Backpack/activity-log/assets/1032474/c7653b9e-55d7-4f82-bd60-97cde828eee8">

### How I see it implemented

I think there are some quick fixes we can do to improve how this looks:
- [x] 🔴 make the show content span across 12 columns (full-width)
- [x] 🔴 the table column right now has a max-width of 480px; this doesn't really make sense here;

Those two alone would help it look like this:

<img width="1279" alt="CleanShot 2023-08-29 at 10 52 45@2x" src="https://github.com/Laravel-Backpack/activity-log/assets/1032474/54c3f7ff-8a78-470f-9ef4-da8aff140459">

I think that's much better already. If we want to go a little further: 
- [x] 🟡 I think it would be SUPER helpful to highlight the attributes that are different, in a certain color. Using basic diffing colors. We could quickly do that with some custom JS, that we inject into the page, and compares the table cell content - if different, it highlights it. So we'd end up with:

<img width="1271" alt="CleanShot 2023-08-29 at 10 59 41@2x" src="https://github.com/Laravel-Backpack/activity-log/assets/1032474/3d457388-fa3e-413a-8203-0c116ced2826">

In my opinion, the above is much more helpful to spot the differences between the old and the new.

**Comment by pxpm** [comment]
I think your last proposal is the better, since I would like to also propose that we only show the diff attributes at first, and maybe add a `[+] Show more` button for the unchaged attributes.

**Comment by tabacitu** [comment]
Update: did the MUST and SHOULDs in https://github.com/Laravel-Backpack/activity-log/pull/15

We can also do the COULD, yes. 

I don't see a lot of benefit in having a "Show unchanged" button. Since this page's whole reason to exist is to show the activity log... if the developer has chosen to log the unchanged... I think the unchanged should be shown. Highlighting is one thing... hiding content is another, if you ask me. 🤷‍♂️

**Comment by tabacitu** [comment]
Since most of the stuff here is done, I'm going to close this issue and open a new one about the COUD-DO - https://github.com/Laravel-Backpack/activity-log/issues/20
