### ISSUE TITLE
[Feature Request] can you save address ip of user or admin

### ISSUE THREAD

**Issue by haythembekir20** [Laravel-Backpack/activity-log#35]
can you add feature to save address ip of user or admin

**Comment by karandatwani92** [comment]
Relates to:
> * https://github.com/spatie/laravel-activitylog/pull/641
> * [Including IP Address of the Causer #39](https://github.com/spatie/laravel-activitylog/issues/39)
> * [IP Address in logs #196](https://github.com/spatie/laravel-activitylog/issues/196)
> * [How to get IP address #161](https://github.com/spatie/laravel-activitylog/issues/161)
> * [Suggestion: include url, ip address, user agent #338](https://github.com/spatie/laravel-activitylog/issues/338)
> * [Can I store the causer ip address ? #384](https://github.com/spatie/laravel-activitylog/issues/384)

**Comment by promatik** [comment]
Hi @haythembekir20!

This package is just a "frontend" for the `spatie/laravel-activitylog`. So this request should be handled in the main package way.
I'll just copy here the answer given at https://github.com/spatie/laravel-activitylog/issues/39, it will be enough to save the IP address.

`AppServiceProvider.php`
```php
Activity::saving(function (Activity $activity) {
    $activity->properties = $activity->properties->put('ip', request()->ip());
});
```

Let us know if it works for you 🙌
