### ISSUE TITLE
[Feature Request] Add pt-BR translation

### ISSUE THREAD

**Issue by WillianDamasceno** [Laravel-Backpack/activity-log#36]
# Feature Request

### Add pt-BR translation

There is only support for `pt` translation natively.

### How I see it implemented

Just duplicate the folder `pt` with the name `pt-BR`.

### What I've already tried to fix it

I was able to solve the problem adding the translation file to the `resources/lang/vendor/backpack.activity-log/pt-BR/activity_log.php` folder.

But it took a white to find out that it should be done like this.
It worked after a lot of different approaches, so in my opinion, the module should provide the `pt-BR` translation since it's the same as the `pt` one.

### Would I be able to work on this myself and submit a PR

Yes, I can solve the problem by just duplicating the folder `pt` with the name `pt-BR`.

My native language is Brazilian Portuguese, I've checked the Portugal Portuguese translation, and it matches the `pt-BR` translation.

One of the things I've tried to test was renaming the `pt` folder to `pt-BR` when it was still inside of `vendor` and it worked, so by just duplicating the folder with the name `pt-BR` would solve the problem for every one that needs Brazilian Portuguese in this module.

**Comment by jcastroa87** [comment]
Hi @WillianDamasceno I will ask our team member @pxpm to check about this feature request.

Cheers.

**Comment by pxpm** [comment]
Hey @WillianDamasceno it's done in 2.0.2. 

Thanks 🙏

**Comment by WillianDamasceno** [comment]
Hey @pxpm, it's working as expected, thank you so much :)
