### ISSUE TITLE
[Bug] Override routes

### ISSUE THREAD

**Issue by adriallongarriu** [Laravel-Backpack/activity-log#47]
# Bug report

### What I did

Like similar add-ons i need to make some adjustments and i try to override the routes to point to my classes extendeing the original backpack calss. I created a file `routes\backpack\activity-log.php` with the routes but my changes were not being applied.

### What I expected to happen

The routes use my classes.

### What happened

In the `src/AutomaticServiceProvider.php` don't have de class `setupRoutes` like other add-ons(NewsCRUD, Settings or PageManager)

```php
    /**
     * Define the routes for the application.
     *
     * @param  \Illuminate\Routing\Router  $router
     * @return void
     */
    public function setupRoutes(Router $router)
    {
        // by default, use the routes file provided in vendor
        $routeFilePathInUse = __DIR__ . $this->routeFilePath;

        // but if there's a file with the same name in routes/backpack, use that one
        if (file_exists(base_path() . $this->routeFilePath)) {
            $routeFilePathInUse = base_path() . $this->routeFilePath;
        }

        $this->loadRoutesFrom($routeFilePathInUse);
    }
```

### What I've already tried to fix it

I move the routes from `routes\backpack\activity-log.php` to `routes\backpack\custom.php`.
It works but it's strange that in some addons it has to be done one way and in others another. It should be unified and always be the same.

### Context to replicate the bug - Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
backpack/activity-log: 2.0.6
```

**Comment by karandatwani92** [comment]
Hey @adriallongarriu 

I do it by following way. I see some parts of the docs saying the same thing. Steps:

1. Create a class and extend the original class. This you have already done.
2. Tell your Laravel App to use your Class if the original one was accessed. This can be done by binding it in the `AppServiceProvider.php`:
```php
public function register(): void
    {
        $this->app->bind(
            \Backpack\PermissionManager\app\Http\Controllers\UserCrudController::class, //this is package controller
            \App\Http\Controllers\Admin\UserCrudController::class //this should be your own controller
        );

        $this->app->bind(
            \Backpack\Settings\app\Http\Controllers\SettingCrudController::class, //this is package controller
            \App\Http\Controllers\Admin\SettingCrudController::class //this should be your own controller
        );

        $this->app->bind(
            \Backpack\PageManager\app\Http\Controllers\Admin\PageCrudController::class, //this is package controller
            \App\Http\Controllers\Admin\PageCrudController::class //this should be your own controller
        );

        $this->app->bind(
            \Backpack\MenuCRUD\app\Http\Controllers\Admin\MenuItemCrudController::class, //this is package controller
            \App\Http\Controllers\Admin\MenuItemCrudController::class //this should be your own controller
        );
        $this->app->bind(
            \Backpack\PermissionManager\app\Http\Controllers\RoleCrudController::class, //this is package controller
            \App\Http\Controllers\Admin\RoleCrudController::class //this should be your own controller
        );
        $this->app->bind(
            \Backpack\PermissionManager\app\Http\Controllers\PermissionCrudController::class, //this is package controller
            \App\Http\Controllers\Admin\PermissionCrudController::class //this should be your own controller
        );
    }
```
    
And now, the package routes will start using your classes.

**Comment by karandatwani92** [comment]
Feel free to reopen - if you feel the question is unanswered.
