### ISSUE TITLE
[Feature Request] Log client-side (JS) errors too, for FREE.

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/activity-log#9]
# Feature Request

### What I am trying to achieve
We can log client-side (JS) errors too.
There are many third-party services available to track JS errors. Why not offer a way to do the same for FREE?

### How I see it implemented

1. Implement an API to receive errors via Ajax call on the `error` event.
2. A small JS snippet for developers to copy-paste into the layout view

DONE🎉

**Comment by tabacitu** [comment]
Nope. Out of scope.
